sudo: false

language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSER_ROOT_VERSION=4.0.x-dev

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL INSTALLER_VERSION=4.0.x-dev PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL INSTALLER_VERSION=4.1.x-dev PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL INSTALLER_VERSION=4.1.x-dev PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL INSTALLER_VERSION=4.x-dev PHPUNIT_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - echo $INSTALLER_VERSION
  - composer require --prefer-source --no-update silverstripe/recipe-cms:1.1.x-dev
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.0.x-dev; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
  - vendor/bin/sake flush=all

  - php vendor/silverstripe/framework/tests/dump_constants.php

script:
  - if [[ $PHPUNIT_TEST ]]; then find . | grep Sapphire && vendor/bin/phpunit tests/; fi

branches:
  only:
    - master
